# Generated by Django 5.0.2 on 2024-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('premium', 'Premium')], default='client', max_length=10),
        ),
    ]
